# Generated by Django 3.0.8 on 2020-08-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RealFollower', to=settings.AUTH_USER_MODEL)),
                ('Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhoFollowed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowedWho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followed', to=settings.AUTH_USER_MODEL)),
                ('Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FollowerUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
